- .kitchen.yml
- Berksfile
- Karamelfile
- attributes/default.rb
- metadata.rb
- providers/start.rb
- recipes/historyserver.rb
- recipes/install.rb
- recipes/master.rb
- recipes/worker.rb
- recipes/yarn.rb
- release.sh
- templates/default/slaves.erb
- templates/default/spark-defaults.conf.erb
- templates/default/spark-env.sh.erb
- test/integration/default/serverspec/localhost/services_spec.rb
Change to dot notation. Hadoop cookbook has been renamed to 'apache_hadoop'.
> Apache hadoop

- attributes/default.rb
- templates/default/spark-defaults.conf.erb
Following
http://spark.apache.org/docs/latest/configuration.html#encryption
> ssl attributes / conf for spark

- attributes/default.rb
- recipes/historyserver.rb
- templates/default/spark-defaults.conf.erb
correct problem with spark history server port not being the same everywhere
> fix Spark history server conf 

- attributes/default.rb
- recipes/yarn.rb
Changes to karamelfile to support ssl, some ssl attrs.
> support for Ssl

- recipes/historyserver.rb
Create directories in HDFS as superuser, which already belongs to certs group and has the correct permissions to use the certificates
> Create directories in HDFS as superuser

- recipes/yarn.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-148
> Yarn shuffle jar [HOPSWORKS-148]

- recipes/historyserver.rb
- templates/default/log4j.properties.erb
change log4j.properties to ensure that the history server logs never take too much place
> change log4j.properties

- attributes/default.rb
- recipes/install.rb
- recipes/yarn.rb
- Download Spark/Orc/Hive dependencies into SPARK_HOME/jars
> Spark hive dep

- recipes/historyserver.rb
https://github.com/hopshadoop/hops-testing/pull/20
> HOPSWORKS-382

- attributes/default.rb
Reverts hopshadoop/spark-chef#36
> Revert "HOPSWORKS-444"

- templates/default/spark-blacklisted-properties.txt.erb
- templates/default/spark-defaults.conf.erb
comment out spark.local.dir and add it to blacklisted properties so users cannot change it
> HOPSWORKS-444

- attributes/default.rb
- recipes/install.rb
- recipes/yarn.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-445
> [HOPSWORKS-445] Downloader support for karamel

- attributes/default.rb
> HOPSWORKS-481

- recipes/yarn.rb
https://github.com/hopshadoop/hops-testing/pull/101
> HOPSWORKS-572

- recipes/install.rb
- recipes/yarn.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-587
> [HOPSWORKS-587] Chef recipe bugfixes

- recipes/yarn.rb
Testing: https://github.com/hopshadoop/hops-testing/pull/115
> [HOPSWORKS-599] Kafka tour broken because of HOPSWORKS-587

- recipes/yarn.rb
Testing: https://github.com/hopshadoop/hops-testing/pull/119
> [HOPSWORKS-605] Fix remote path for hops-examples and hops-util

- attributes/default.rb
- recipes/install.rb
- recipes/yarn.rb
- templates/default/app.log4j.properties.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-627
Also a  bugfix in the ownership of the spark directory.
> [HOPSWORKS-627] make spark user a system user

- attributes/default.rb
- recipes/yarn.rb
- Add tf-spark-connector for converting between spark dataframes and TFRecords
> [HOPSWORKS-718] Feature Store in HopsML

- .gitignore
- attributes/default.rb
- metadata.rb
- recipes/yarn.rb
- Move spark-examples chef attributes from hops-hadoop-chef
- Add featurestore example jar
> [HOPSWORKS-853] Feature Store Tour

- attributes/default.rb
- metadata.rb
- recipes/install.rb
- recipes/yarn.rb
- Add spark-avro package dependency
> [HOPSWORKS-912] Support image and avro data types (featurestore)

- recipes/historyserver.rb
- templates/default/sparkhistoryserver.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1091
> [HOPSWORKS-1091] add systemd unit file dep

- attributes/default.rb
- metadata.rb
- recipes/yarn.rb
Feature Store Util tool for:
- creating training datasets from UI
- creating feature groups from UI
- updating training dataset stats from UI
- updating feature group stats from UI
> [HOPSWORKS-1196] Feature Store V2

- recipes/install.rb
- templates/default/spark-env.sh.erb
Speed up YARN job submission by using local python archives.
> [HOPSWORKS-453] Configure Spark to use local Python archives

- attributes/default.rb
- metadata.rb
- recipes/install.rb
- Add hudi jars to spark installation
> [HOPSWORKS-34] Hudi for unified Stream/Batch processing

- metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1225
> [HOPSWORKS-1225] add spark url attribute in metatadata

- attributes/default.rb
- recipes/yarn.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1265
> [HOPSWORKS-1265] Put Hops verification jar to hdfs

- metadata.rb
- Fix missing attribute in metadata.rb
> [HOPSWORKS-1139] Online feature store

- recipes/yarn.rb
Download the binaries of the feature store import jobs when
installing the enterprise edition.
> [HOPSWORKS-1304] Download import jobs for enterprise

- recipes/certs.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1021
> [HOPSWORKS-1021][Append] Fix HDFS operation user

- recipes/yarn.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1334
Copies an additional feature store helper job `ft_trainingdataset_sql_job.py` into HDFS in directory `/user/spark/`
> [HOPSWORKS-1334] Add SQL Query featurestore-helper job

- attributes/default.rb
- recipes/certs.rb
- recipes/install.rb
- templates/default/hive-site.xml.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1425
> [HOPSWORKS-1425] change hdfs prefix to hopsfs

- recipes/historyserver.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1457
> [HOPSWORKS-1457] fix systemd script

- attributes/default.rb
- recipes/install.rb
https://github.com/logicalclocks/hops-testing/pull/567
tests: https://github.com/logicalclocks/hops-testing/pull/567
> [HOPSWORKS-1476] Add support for elasticsearch spark connector

- Berksfile
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1679
> [HOPSWORKS-1679] pin version of java in Berksfile

- Berksfile
Reverts logicalclocks/spark-chef#90
> Revert "[HOPSWORKS-1679] pin version of java in Berksfile"

- attributes/default.rb
- metadata.rb
- providers/start.rb
- recipes/historyserver.rb
- recipes/install.rb
- recipes/master.rb
- recipes/worker.rb
- recipes/yarn.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1694
> [HOPSWORKS-1694] run user code in docker

- recipes/historyserver.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
> [HOPSWORKS-1862] Fix cyclic dependency error

- recipes/install.rb
- templates/default/spark-env.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1895
> [HOPSWORKS-1895] Bind Spark History Server to any address

- recipes/historyserver.rb
- templates/default/sparkhistoryserver.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2053
> [HOPSWORKS-2053] Sparkhistoryserver should wait until NN Consul domain name becomes resolvable

- attributes/default.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1986
>  [HOPSWORKS-1986] Add snowflake connector jar file 

- templates/default/sparkhistoryserver.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units

- templates/default/sparkhistoryserver.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Wait before each restart
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
> [HOPSWORKS-2065] Automatically restart failed systemd units (#108)

- attributes/default.rb
- recipes/install.rb
This reverts commit e7a23b856451f788b499f5d181a625cc170714e7.
> Revert "[HOPSWORKS-1986] Add snowflake connector jar file (#105)"

- attributes/default.rb
- metadata.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/projects/HOPSWORKS/issues/HOPSWORKS-2189
built with https://github.com/logicalclocks/spark/pull/22
> [HOPSWORKS-2189] Update spark-avro package for to_avro/from_avro methods

- templates/default/sparkhistoryserver.service.erb
fixes https://logicalclocks.atlassian.net/browse/HOPSWORKS-2292
> [HOPSWORKS-2292] remove systemd waiting mechanism

- attributes/default.rb
- metadata.rb
- recipes/install.rb
logicalclocks/hops-testing-ee/pull/279
> [HOPSWORKS-2314] add snowflake jars to spark

- recipes/install.rb
Chef tries to resolve the attrs even though they are in comments, and they are null.
> remove snowflake attrs from install recipe, compile error

- attributes/default.rb
- recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
> [HOPSWORKS-2578] Move Spark logs under data volume

- attributes/default.rb
- recipes/install.rb
Add gcs-connector-hadoop3-2.2.5-shaded.jar to /spark/hopsworks-jars
> [HOPSWORKS-2890] add gcs connector jar

- attributes/default.rb
Related to https://github.com/logicalclocks/spark/pull/31
> [HOPSWORKS-3233] Bump spark to 3.1.1.3

- recipes/yarn.rb
https://hopsworks.atlassian.net/browse/HWORKS-297
> [HWORKS-297] Retry package resource

- attributes/default.rb
- metadata.rb
- recipes/install.rb
This reverts commit 993536aee8d707ba8fdaf77fd5b04a77c9fd6ada.
> Revert "[HWORKS-510] Archive hops-util Java (#169)"

- attributes/default.rb
- recipes/install.rb
(#170)"
This reverts commit b3b8c8df9ab4e6090961d042bc2594e30e71b56f.
> Revert "[FSTORE-816] Add Kafka Datasource Jar file to spark deployment (#170)"

- attributes/default.rb
- metadata.rb
- recipes/install.rb
This reverts commit c9586f24cb92c48123406b4bceac72cd6abf6d7a.
> Revert "Revert "[HWORKS-510] Archive hops-util Java (#169)" (#172)"

- attributes/default.rb
- recipes/install.rb
This reverts commit 4a39e427e245f16a4346c0507fe37854bffdf119.
> Revert "Revert "[FSTORE-816] Add Kafka Datasource Jar file to spark deployment (#170)" (#173)"

- metadata.rb
- recipes/config.rb
- recipes/yarn.rb
https://hopsworks.atlassian.net/browse/HWORKS-606
> [HWORKS-606] Disassociate Spark configuration from HopsFS artifacts so we can include the recipe from other places

- attributes/default.rb
- metadata.rb
https://hopsworks.atlassian.net/browse/HWORKS-637
> [HWORKS-637] Add attribute to specify release candidate version for hsfs

- recipes/yarn.rb
Fixes https://hopsworks.atlassian.net/browse/FSTORE-857
> [FSTORE-857] Remove version from hsfs utils to avoid upgrade issues

- attributes/default.rb
- templates/default/spark-env.sh.erb
- templates/default/sparkhistoryserver.service.erb
- templates/default/start-history-server.sh.erb
https://hopsworks.atlassian.net/browse/HWORKS-659
> [HWORKS-659] Configure the tmp directory for Java and set the pid directory
